@Library('olcne-pipeline')
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
    branchPattern: new BranchPattern(master: 'release/.*', feature: '(?!^release/.*$)(^.*$)'),
    customStages: [container: [enabled: false]],
    golang: '1.22.5',
    platforms: ['ol8', 'ol9'],
    architectures: ['x86_64', 'aarch64'],
    ol8ModulesToDisable: ['go-toolset:ol8'],
    yumOL8Repos: ['ol8_codeready_builder', 'ol8_UEKR7'],
    yumOL9Repos: ['ol9_codeready_builder', 'ol9_UEKR7'],
    preBuildCommands: [
      "make build/catalog",
    ],
)
